version: '3'
services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./:/var/www/html
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - app-network
  php74:
    build:
      args:
        user: $USER # your username on your machine, you can get it by running echo $USER
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    image: 7.4-fpm
    ports:
      - "9000:9000"
    volumes:
       - ./:/var/www/html
    networks:
      - app-network
  mysql57:
    image: mysql:5.7.32
    container_name: mysql57
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
 
#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  
